### ISSUE TITLE
Type BindingSetAssignment not supported for cost estimation.

### ISSUE THREAD

**Issue by tfrancart** [VeritasOS/fedx#4]
Hello

I need FedX to work with the VALUES keyword, which is not the case at the moment. See test query below :

```
SELECT DISTINCT  ?this
WHERE
  { ?this  a                     <http://www.cidoc-crm.org/cidoc-crm/E22_Man-Made_Object> .
    ?this <http://www.ics.forth.gr/isl/CRMarchaeo/AP21i_is_contained_in> ?Site1 .
    ?Site1  a                     <http://www.cidoc-crm.org/cidoc-crm/E27_Site>
    VALUES ?Site1 { <http://arsol.univ-tours.fr/4DACTION/WFICHEWEB/isiteAA> }
  }
```

```
Caused by: com.fluidops.fedx.exception.FedXRuntimeException: Type BindingSetAssignment not supported for cost estimation. If you run into this, please report a bug.
	at com.fluidops.fedx.optimizer.JoinOrderOptimizer.getFreeVars(JoinOrderOptimizer.java:162)
	at com.fluidops.fedx.optimizer.JoinOrderOptimizer.optimizeJoinOrder(JoinOrderOptimizer.java:79)
	at com.fluidops.fedx.optimizer.StatementGroupOptimizer.meetNJoin(StatementGroupOptimizer.java:170)
	at com.fluidops.fedx.optimizer.StatementGroupOptimizer.meetOther(StatementGroupOptimizer.java:78)
	at com.fluidops.fedx.algebra.NJoin.visit(NJoin.java:49)
	at org.eclipse.rdf4j.query.algebra.BinaryTupleOperator.visitChildren(BinaryTupleOperator.java:101)
	at org.eclipse.rdf4j.query.algebra.LeftJoin.visitChildren(LeftJoin.java:87)
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meetNode(AbstractQueryModelVisitor.java:661)
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meetBinaryTupleOperator(AbstractQueryModelVisitor.java:607)
	at org.eclipse.rdf4j.query.algebra.helpers.AbstractQueryModelVisitor.meet(AbstractQueryModelVisitor.java:367)
	at org.eclipse.rdf4j.query.algebra.LeftJoin.visit(LeftJoin.java:76)
```

How can this be enhanced/improved ?

**Comment by tfrancart** [comment]
Thanks ! I will test and let you know

**Comment by tfrancart** [comment]
This works AFAICS
